//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Station0730.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playerr
    {
        public int PlayerID { get; set; }
        public string style { get; set; }
        public string PlayName { get; set; }
        public string SongName { get; set; }
        public string YT_video { get; set; }
    }
}
